### ISSUE TITLE
No show Preview menu button

### ISSUE THREAD

**Issue by marcevrard** [jithurjacob/vscode-nbpreviewer#13] opened 2018-09-29 15:09 UTC
There is no show Preview menu button after installing the extension.
Also the `Show preview` in the  Command Palette gives the error: `command 'extension.showPreview' not found`.
```
vscode-nbpreviewer 1.0.0
VScode 1.27.2
python 3.6.6
macOS 10.13.6
```

**Comment by chinaq** [comment] 2018-09-29 15:58
me too

**Comment by regearhead** [comment] 2018-09-29 19:15
The Show Preview button is missing.
I am unable to get the extension to work. Windows 10, Anaconda 5.2.0.

**Comment by yukw777** [comment] 2018-10-07 04:10
Same here.

**Comment by syagev** [comment] 2018-10-08 19:15
Also with
```
vscode-nbpreviewer 1.0.0
VSCode 1.28.0
python 3.6.6
win10 build1809
```

**Comment by jacobdanovitch** [comment] 2018-10-17 16:50
Same here on Windows and Ubuntu.

**Comment by akamlani** [comment] 2018-10-24 19:12
Any resolution on this yet?

**Comment by alexsivris** [comment] 2018-11-10 09:14
Same problem on my system:
OS: macOS 10.14.1
nbpreviewer version: 1.0.0

**Comment by AlJohri** [comment] 2018-11-14 01:54
same here. ping @jithurjacob

**Comment by carbocation** [comment] 2018-11-17 18:54
I can confirm this problem on Ubuntu 18.04. Specifically, the "Preview" button is no longer available.

**Comment by mUtterberg** [comment] 2018-11-21 15:19
Same here. Is someone working on this issue at the moment? Even if it's not ready, it'd help to know the status on that.

**Comment by carbocation** [comment] 2018-11-21 16:21
This is now happening on all of my devices (including OS X). I'm wondering if this is a consequence of the October 2018 vscode update.

**Comment by jithurjacob** [comment] 2018-12-04 18:20
Apologies for the delay. I was going through some personal issues. I have published a new version after testing on my MacBook Pro. Please confirm if the issue is solved.

**Comment by pwolter** [comment] 2018-12-05 07:41
The issue is not resolved. Still is not available.
The Show preview in the Command Palette gives the error: command 'extension.showPreview' not found.

**Comment by tribbloid** [comment] 2018-12-07 02:12
also affects me. Has any one found the reason?

**Comment by carbocation** [comment] 2018-12-10 23:35
It sounds like there is a fix, but also that it's not working for many of us. Is there a log of some sort that we can post to help troubleshoot? (It's still not working for me on OS X or Linux.)

**Comment by jithurjacob** [comment] 2018-12-15 06:39
@carbocation @tribbloid @pwolter 

Could you please provide a screen shot with your developer console open. Please follow the below steps.

1. Click Help > Toggle Developer Tools
2. Open a Jupyter notebook

<img width="1440" alt="screenshot 2018-12-15 at 12 04 28 pm" src="https://user-images.githubusercontent.com/7101452/50040024-38b9b380-0062-11e9-84a9-0396514b8736.png">

**Comment by abhinavmathur96** [comment] 2018-12-15 09:45
The "Show Preview" button is not visible
![untitled](https://user-images.githubusercontent.com/13285071/50041520-3fedbb00-007c-11e9-8fc9-6571415c7614.png)


VScode 1.30.0
Win10 build 1803

**Comment by carbocation** [comment] 2018-12-15 12:53
@jithurjacob Attached:
![image](https://user-images.githubusercontent.com/218804/50043224-507f4080-003e-11e9-877d-40943db9b49f.png)

Possibly notable part:
```
[jithurjacob.nbpreviewer]: Command `extension.showPreview` appears multiple times in the `commands` section.
```

Version info from VS Code -> About:
```
Version: 1.30.0
Commit: c6e592b2b5770e40a98cb9c2715a8ef89aec3d74
Date: 2018-12-11T22:21:33.585Z
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 4.15.0-42-generic
```

**Comment by carbocation** [comment] 2018-12-15 13:32
The extension name is ms-python.python. [URL is here.](https://marketplace.visualstudio.com/items?itemName=ms-python.python) 

[I opened up an issue](https://github.com/Microsoft/vscode-python/issues/3714) since this seems like it might be a problem with their extension.

**Comment by jithurjacob** [comment] 2018-12-15 13:49
Thank you @carbocation. I will also keep an eye on the issue.

**Comment by jithurjacob** [comment] 2018-12-24 08:52
@carbocation I've updated the extension. Could you please check if it fixed the issue?

**Comment by chaoyuxie** [comment] 2018-12-24 08:59
@jithurjacob Thank you. The Preview menu button shows in the vscode

**Comment by jithurjacob** [comment] 2018-12-24 12:02
@chaoyuxie Thank you for confirming. Please do leave good review.

**Comment by jithurjacob** [comment] 2018-12-24 12:02
Closing the issue

**Closed by jithurjacob** 2018-12-24 12:02 UTC
