### ISSUE TITLE
command 'extension.showPreview' not found

### ISSUE THREAD

**Issue by pjkasper** [jithurjacob/vscode-nbpreviewer#1] opened 2018-01-16 14:24 UTC
VS Code
Version 1.19.2
Commit 490ef761b76b3f3b3832eff7a588aac891e5fe80
Date 2018-01-10T16:16:25.767Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture ia32

**Comment by jithurjacob** [comment] 2018-01-16 15:24
Hi, 

This happens when we press the extension is still being loaded. I'm working on a fix for this. Meanwhile please wait for sometime for the extension to load.

You could view the extension loading status by doing the following
Help> Toggle Developer Tools> Console

Open an IPython notebook wait till the following message is showed in the console "Congratulations, your extension "nbpreviewer" is now active!"

**Comment by MrSassyBritches** [comment] 2018-03-11 17:40
how long should it take to load? because I cannot see this message.

**Comment by tigerhawkvok** [comment] 2018-03-16 16:53
@jithurjacob never loads at all for me (even over days) of the editor being open). Let me know if there's a message that I can send from the console that will help you debug this.

**Comment by JobLeonard** [comment] 2018-03-20 10:14
Same issue on my laptop (Win10, Anaconda 5). I don't use Jupyter all that much, but many of the people in the research group I program for use VSCode for their Python editing, so this looks great for them! I want to be able to recommend it to them without having to get a sad "doesn't work for me" response.

@jithurjacob, since you say this would be tackled in the next release, I guess you have an idea what causes the slowdown. Could you give an overview of that so we can look for hints where the issues might be on our systems for better feedback?

Does the installed version of Jupyter matter?

**Comment by chaoyuxie** [comment] 2018-11-22 15:29
Hi, the command 'extension.showPreview' not found.

**Comment by jithurjacob** [comment] 2018-12-04 18:14
Apologies for the delay. I was going through some personal issues. I have published a new version after testing on my MacBook Pro. Please confirm if the issue is solved.

**Comment by JobLeonard** [comment] 2018-12-04 21:14
Can't check right now as I switched machines and haven't used Jupyter on my new one yet (also switched to Linux), but you have my sympathies regarding "personal issues". Whatever they are, hang in there!

**Comment by jithurjacob** [comment] 2018-12-05 06:48
@JobLeonard  Thank you

**Comment by AhmetGurbuzz** [comment] 2018-12-05 18:20
@jithurjacob it is still giving error for me, I am on win 8.1, vs code 1.29.1

**Comment by jithurjacob** [comment] 2018-12-15 06:35
@AhmetGurbuzz  Could you please provide a screen shot with your developer console open. Please follow the below steps.

1. Click Help > Toggle Developer Tools
2. Open a Jupyter notebook

<img width="1440" alt="screenshot 2018-12-15 at 12 04 28 pm" src="https://user-images.githubusercontent.com/7101452/50039966-a1ecf700-0061-11e9-9291-675240f969a0.png">

**Comment by micmelesse** [comment] 2018-12-15 18:33
@jithurjacob I am also having the same issue. Here is a screenshot. 
![sharedscreenshot](https://user-images.githubusercontent.com/16394078/50046230-e8882480-0054-11e9-8f5b-18ab2120f181.jpg)

**Comment by jithurjacob** [comment] 2018-12-24 08:53
@micmelesse I've updated the extension. Could you please try again?

**Comment by jithurjacob** [comment] 2018-12-25 06:49
Awesome. Closing the issue.

**Closed by jithurjacob** 2018-12-25 06:49 UTC

**Comment by WadeeaKiwan** [comment] 2019-01-26 00:06
Would you please help me?

I have tried to open the live html previwer but I've got this messege:
command 'extension.sidePreview' not found
![2019-01-26 01_03_34- test txt - hyf course - visual studio code](https://user-images.githubusercontent.com/44202964/51779931-cc26df80-210a-11e9-9d55-86d373cab886.jpg)

**Comment by jithurjacob** [comment] 2019-01-26 05:34
@WadeeaKiwan  Please post your VS code version and the extension version. Ensure that both are up to date.

**Comment by WadeeaKiwan** [comment] 2019-01-26 09:11
@jithurjacob Thanks for replying. I installed them yesterday, VS code from the website of Visual Studio and the Live HTML Previewer from the marketplace. The operating system of my laptop is Windows 10 Home X64

VS code version: 1.30.2
Live HTML Previewer version: 0.3.0

**Comment by jithurjacob** [comment] 2019-01-26 09:16
@WadeeaKiwan This GitHub repo is not for "Live HTML Previewer version" it is for "Jupyter Notebook Previewer" https://marketplace.visualstudio.com/items?itemName=jithurjacob.nbpreviewer 

Please create an issue in https://github.com/HarshdeepGupta/live-html-preview

**Comment by WadeeaKiwan** [comment] 2019-01-26 09:53
@jithurjacob Thanks a lot! It works now!
